[package]
name = "config-file-events"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "config_file_events"
path = "src/main.rs"

[dependencies]
osquery-rust = { path = "../../osquery-rust" }
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"